'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import { StoreProvider } from '@/utils/Store';
import { Providers } from '@/provider';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Ecommece web',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <StoreProvider>{children}</StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
